# Generated by Django 6.0.2 on 2026-02-20 08:22

from django.db import migrations, models


def set_initial_free_agent_services(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(code="C_STANDARD").update(free_agent_services=3)
    Plan.objects.filter(code="C_PREMIUM").update(free_agent_services=99)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_provider_to_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="free_agent_services",
            field=models.PositiveIntegerField(
                default=0,
                help_text="고객 플랜 전용. Standard 등에서 Agent 약속 신청을 N회까지 무료 제공. 0=없음.",
                verbose_name="무료 Agent 서비스 횟수",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.CharField(
                choices=[
                    ("C_BASIC", "Basic"),
                    ("C_STANDARD", "Standard"),
                    ("C_PREMIUM", "Premium"),
                    ("P_BASIC", "Basic"),
                    ("P_STANDARD", "Standard"),
                    ("P_PREMIUM", "Premium"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=models.JSONField(
                blank=True, default=dict, help_text="플랜 기능 목록 (JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="target_role",
            field=models.CharField(
                choices=[("CUSTOMER", "고객"), ("AGENT", "에이전트")], max_length=20
            ),
        ),
        migrations.RunPython(set_initial_free_agent_services, migrations.RunPython.noop),
    ]
