# Generated by Django 6.0.2 on 2026-02-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_plan_duration_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="표시용 이름. 예: 스탠다드, 프리미엄",
                max_length=100,
                verbose_name="요금제 이름",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C_BASIC", "Basic"),
                    ("C_STANDARD", "Standard"),
                    ("C_PREMIUM", "Premium"),
                    ("P_BASIC", "Basic"),
                    ("P_STANDARD", "Standard"),
                    ("P_PREMIUM", "Premium"),
                ],
                help_text="레거시/시드용. 비워두면 이름으로만 표시.",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="tier",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "베이직"), (2, "스탠다드"), (3, "프리미엄")],
                help_text="레거시용. 비워두면 표시만 이름 사용.",
                null=True,
            ),
        ),
    ]
