# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_plan_name_and_optional_code_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="can_use_llm",
            field=models.BooleanField(
                blank=True,
                help_text="체크 시 AI 서비스 이용 가능. 비워두면 tier/기본값 적용.",
                null=True,
                verbose_name="LLM(AI) 서비스 사용",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="has_agent_assistance",
            field=models.BooleanField(
                blank=True,
                help_text="체크 시 필요 시 에이전트 도움 가능. 비워두면 tier 적용.",
                null=True,
                verbose_name="에이전트 도움(필요 시)",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="has_full_agent_assistance",
            field=models.BooleanField(
                blank=True,
                help_text="체크 시 모든 항목 에이전트 도움. 비워두면 tier 적용.",
                null=True,
                verbose_name="전체 항목 에이전트 도움",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="can_contract_package_or_single",
            field=models.BooleanField(
                blank=True,
                help_text="체크 시 패키지·단일 항목 계약 가능. 비워두면 tier 적용.",
                null=True,
                verbose_name="패키지/단일 계약 가능",
            ),
        ),
    ]
