# Generated by Django 6.0.2 on 2026-02-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_message_detected_lang_body_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(max_length=20, verbose_name="언어 코드"),
                ),
                ("body", models.TextField(blank=True, verbose_name="번역된 본문")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations_by_lang",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지 번역",
                "verbose_name_plural": "메시지 번역",
                "ordering": ["language_code"],
                "unique_together": {("message", "language_code")},
            },
        ),
    ]
