# Generated by Django 6.0.2 on 2026-03-11 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_customer_request_intent_proposal_log"),
        ("survey", "0020_submission_revision_count_reopened_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRequestFeedbackEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        db_index=True,
                        help_text="동일 수정 요청 흐름을 묶는 식별자 (UUID 또는 analysis_id 등).",
                        max_length=64,
                        verbose_name="요청 흐름 ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("message_received", "메시지 수신"),
                            ("route_predicted", "경로 예측"),
                            ("suggestion_clicked", "추천 클릭"),
                            ("page_viewed", "페이지 조회"),
                            ("edit_saved", "수정 저장"),
                            ("feedback_clicked", "피드백 클릭"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="이벤트 유형",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        blank=True,
                        help_text="step 번호, section id, 또는 페이지 식별자.",
                        max_length=64,
                        null=True,
                        verbose_name="페이지 키",
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        blank=True,
                        help_text="message_received 시 원문, 기타 이벤트 시 보조 텍스트.",
                        null=True,
                        verbose_name="메시지 텍스트",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="이벤트별 상세 데이터. route_predicted: heuristic_page, llm_page, top_candidates, final_recommended_pages / edit_saved: changed_fields, save_result, entity_type, entity_id / feedback_clicked: value 등.",
                        verbose_name="메타데이터",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="발생 시각"),
                ),
            ],
            options={
                "verbose_name": "요청 피드백 이벤트",
                "verbose_name_plural": "요청 피드백 이벤트",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="customeractionfeedbacklog",
            new_name="messaging_c_proposa_85f88f_idx",
            old_name="messaging_c_proposa_j1k2l3_idx",
        ),
        migrations.RenameIndex(
            model_name="customeractionproposal",
            new_name="messaging_c_status_236735_idx",
            old_name="messaging_c_status_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="customeractionproposal",
            new_name="messaging_c_convers_9ffef1_idx",
            old_name="messaging_c_convers_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrequestintentanalysis",
            new_name="messaging_c_custome_cfe00a_idx",
            old_name="messaging_c_custome_7d3e4f_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrequestintentanalysis",
            new_name="messaging_c_convers_d7ffeb_idx",
            old_name="messaging_c_convers_a1b2c3_idx",
        ),
        migrations.AlterField(
            model_name="customeractionfeedbacklog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROPOSAL_SHOWN", "제안 노출"),
                    ("USER_CONFIRMED", "고객 승인"),
                    ("USER_DECLINED", "고객 거절"),
                    ("ACTION_STARTED", "액션 실행 시작"),
                    ("ACTION_SUCCEEDED", "액션 실행 성공"),
                    ("ACTION_FAILED", "액션 실행 실패"),
                    ("USER_CORRECTED", "고객 정정 요청"),
                    ("FOLLOWUP_SUCCESS", "후속 행동 완료"),
                    ("PROPOSAL_EXPIRED", "제안 만료"),
                    ("ADMIN_OVERRIDE", "Admin 수동 처리"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="이벤트 유형",
            ),
        ),
        migrations.AlterField(
            model_name="customeractionproposal",
            name="proposal_type",
            field=models.CharField(
                choices=[
                    ("SURVEY_REOPEN", "설문 재수정"),
                    ("SURVEY_RESUME", "설문 이어쓰기"),
                    ("QUOTE_RESEND", "견적 재발송"),
                    ("QUOTE_REVISION", "견적 수정 요청"),
                    ("PAYMENT_LINK_RESEND", "결제 링크 재발송"),
                    ("HUMAN_REVIEW", "사람 검토 요청"),
                    ("INFO_REPLY", "정보 안내"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="제안 유형",
            ),
        ),
        migrations.AddField(
            model_name="customerrequestfeedbackevent",
            name="survey_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_events",
                to="survey.surveysubmission",
                verbose_name="설문 제출",
            ),
        ),
        migrations.AddField(
            model_name="customerrequestfeedbackevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_feedback_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="customerrequestfeedbackevent",
            index=models.Index(
                fields=["request_id", "event_type"],
                name="messaging_c_request_f030a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerrequestfeedbackevent",
            index=models.Index(
                fields=["request_id", "-created_at"],
                name="messaging_c_request_5d357d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerrequestfeedbackevent",
            index=models.Index(
                fields=["survey_submission", "-created_at"],
                name="messaging_c_survey__ca248d_idx",
            ),
        ),
    ]
