# Generated by Django 6.0.2 on 2026-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_add_customer_request_feedback_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrequestintentanalysis",
            name="request_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="한 번의 수정 요청 흐름을 묶는 UUID. feedback 이벤트·타임라인 조회용.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="요청 세션 ID",
            ),
        ),
    ]
