# Generated by Django 6.0.2 on 2026-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0014_manual_label_revision_history"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customerrequestlearningsummary",
            new_name="messaging_c_label_q_1dc760_idx",
            old_name="messaging_c_label_q_8e0e0d_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrequestmanuallabelrevision",
            new_name="messaging_c_request_8937de_idx",
            old_name="messaging_c_request_e91f7b_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrequestmanuallabelrevision",
            new_name="messaging_c_learnin_87bd08_idx",
            old_name="messaging_c_learnin_6c715c_idx",
        ),
        migrations.AlterField(
            model_name="customerrequestintentanalysis",
            name="source",
            field=models.CharField(
                choices=[
                    ("heuristic", "휴리스틱 규칙"),
                    ("semantic", "시맨틱 유사도"),
                    ("semantic_safe", "시맨틱 유사도(안전 게이트)"),
                    ("semantic_local", "시맨틱+로컬 앙상블"),
                    ("semantic_local_safe", "시맨틱+로컬 앙상블(안전 게이트)"),
                    ("gemini", "Gemini LLM"),
                    ("ollama", "Ollama LLM"),
                    ("stub", "Stub (미연동)"),
                    ("retrieval", "검색 기반"),
                    ("local_classifier", "로컬 분류기"),
                    ("local_classifier_safe", "로컬 분류기(안전 게이트)"),
                    ("quote_llm", "견적 변경 LLM"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="분류 소스",
            ),
        ),
    ]
