# Generated by Django 5.2.12 on 2026-03-15 11:34

import translations.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_corporate_ad_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='gradient_css',
            field=models.CharField(blank=True, help_text=translations.utils.DisplayKey('예: linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%)'), max_length=200, verbose_name=translations.utils.DisplayKey('그라데이션 CSS')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name=translations.utils.DisplayKey('배경 이미지')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=translations.utils.DisplayKey('표시')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='link_url',
            field=models.URLField(blank=True, help_text=translations.utils.DisplayKey('광고 등 클릭 시 이동할 URL'), verbose_name=translations.utils.DisplayKey('링크 URL')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name=translations.utils.DisplayKey('정렬')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='placement',
            field=models.CharField(choices=[('HOME_INTRO', '홈인트로'), ('SETTLEMENT', '정착서비스'), ('CORPORATE', '기업서비스'), ('AD', '광고')], db_index=True, default='HOME_INTRO', max_length=20, verbose_name=translations.utils.DisplayKey('노출 위치')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name=translations.utils.DisplayKey('부제목')),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(max_length=200, verbose_name=translations.utils.DisplayKey('제목')),
        ),
        migrations.AlterField(
            model_name='content',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text=translations.utils.DisplayKey('접근 허용 역할 (GUEST=비로그인, CUSTOMER, AGENT, ADMIN)')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='ad_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name=translations.utils.DisplayKey('광고 부제목')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='ad_title',
            field=models.CharField(max_length=200, verbose_name=translations.utils.DisplayKey('광고 제목')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name=translations.utils.DisplayKey('회사/업체명')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='contact_name',
            field=models.CharField(max_length=100, verbose_name=translations.utils.DisplayKey('담당자명')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=translations.utils.DisplayKey('이메일')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='link_url',
            field=models.URLField(verbose_name=translations.utils.DisplayKey('링크 URL')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='memo',
            field=models.TextField(blank=True, verbose_name=translations.utils.DisplayKey('추가 요청사항')),
        ),
        migrations.AlterField(
            model_name='corporateadrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name=translations.utils.DisplayKey('연락처')),
        ),
    ]
