# Generated by Django 6.0.2 on 2026-02-19 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementQuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "services",
                    models.JSONField(default=list, verbose_name="선택 서비스"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="연락처"),
                ),
                ("memo", models.TextField(blank=True, verbose_name="추가 문의사항")),
                (
                    "ai_suggested",
                    models.BooleanField(default=False, verbose_name="AI 추천 사용"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_quotes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "견적 신청",
                "verbose_name_plural": "견적 신청",
                "ordering": ["-created_at"],
            },
        ),
    ]
