# Generated by Django 6.0.2 on 2026-02-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0004_seed_services"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settlementservice",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "서비스 항목",
                "verbose_name_plural": "서비스 항목",
            },
        ),
        migrations.RemoveField(
            model_name="settlementservice",
            name="ordering",
        ),
    ]
