# Generated by Django 6.0.2 on 2026-02-20 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0008_add_agent_appointment_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettlementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="이주 State"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="도시"),
                ),
                (
                    "entry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="입국/이주 예정일"
                    ),
                ),
                (
                    "service_schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"YYYY-MM-DD": [{"code":"X","label":"Y"}, ...]}',
                        verbose_name="서비스 일정",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_plan",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 정착 플랜",
                "verbose_name_plural": "사용자 정착 플랜",
            },
        ),
    ]
