# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0010_add_checkout_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentappointmentrequest",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                help_text="취소 시 사유. 예: 사용자 취소, Agent 취소",
                max_length=100,
                verbose_name="취소 사유",
            ),
        ),
    ]
