# Generated by Django 6.0.2 on 2026-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_agent_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_cities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="에이전트가 커버하는 도시 Area ID 목록",
                verbose_name="커버 도시",
            ),
        ),
    ]
