# Generated by Django 5.2.12 on 2026-03-15 11:34

import django.core.validators
import django.db.models.deletion
import translations.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_agent_identity_verification_fields'),
        ('settlement', '0038_alter_settlementquoterequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentforrating',
            options={'verbose_name': translations.utils.DisplayKey('에이전트별 별점'), 'verbose_name_plural': translations.utils.DisplayKey('에이전트별 별점')},
        ),
        migrations.AlterModelOptions(
            name='agentrating',
            options={'ordering': ('-created_at',), 'verbose_name': translations.utils.DisplayKey('에이전트 별점'), 'verbose_name_plural': translations.utils.DisplayKey('에이전트 별점')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': translations.utils.DisplayKey('사용자'), 'verbose_name_plural': translations.utils.DisplayKey('사용자들')},
        ),
        migrations.AlterField(
            model_name='agentrating',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name=translations.utils.DisplayKey('평가 대상 (Agent)')),
        ),
        migrations.AlterField(
            model_name='agentrating',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text=translations.utils.DisplayKey('완료된 약속에 대한 후기일 때만 연결. 약속당 1건만 허용.'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='settlement.agentappointmentrequest', verbose_name=translations.utils.DisplayKey('연결된 약속')),
        ),
        migrations.AlterField(
            model_name='agentrating',
            name='comment',
            field=models.TextField(blank=True, verbose_name=translations.utils.DisplayKey('한줄평')),
        ),
        migrations.AlterField(
            model_name='agentrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name=translations.utils.DisplayKey('평가자 (Customer)')),
        ),
        migrations.AlterField(
            model_name='agentrating',
            name='score',
            field=models.PositiveSmallIntegerField(help_text=translations.utils.DisplayKey('1~5점'), validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name=translations.utils.DisplayKey('별점')),
        ),
        migrations.AlterField(
            model_name='user',
            name='accept_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=translations.utils.DisplayKey('에이전트 전체 약속 수락률. 예: 0.85 = 85%. 비워두면 서비스별 통계에서 계산해 표시.'), max_digits=5, null=True, verbose_name=translations.utils.DisplayKey('Accept rate (수락률)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_accept_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=translations.utils.DisplayKey('레벨 계산 시점 기준 수락률(0~1 권장)'), max_digits=5, null=True, verbose_name=translations.utils.DisplayKey('수락률(스냅샷)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_cities',
            field=models.JSONField(blank=True, default=list, help_text=translations.utils.DisplayKey('에이전트가 커버하는 도시 Area ID 목록'), verbose_name=translations.utils.DisplayKey('커버 도시')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_cities_by_state',
            field=models.JSONField(blank=True, default=dict, help_text=translations.utils.DisplayKey('주별 도시 ID: {"NC": [1,2,3], "CA": [10,11]}'), verbose_name=translations.utils.DisplayKey('커버 도시 (주별)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_completed_service_count',
            field=models.PositiveIntegerField(default=0, help_text=translations.utils.DisplayKey('레벨 계산 시점 기준 완료 서비스 건수'), verbose_name=translations.utils.DisplayKey('완료 서비스 건수(스냅샷)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_identity_verification_status',
            field=models.CharField(choices=[('NOT_REQUIRED', '확인 불필요'), ('REQUIRED', '신분 확인 서류 필요'), ('SUBMITTED', '신분 확인 서류 제출됨'), ('VERIFIED', '신분 확인 완료')], db_index=True, default='NOT_REQUIRED', help_text=translations.utils.DisplayKey('최초 온보딩 시 신분증 확인이 필요한 Agent 여부와 처리 상태'), max_length=20, verbose_name=translations.utils.DisplayKey('Agent 신분 확인 상태')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_identity_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=translations.utils.DisplayKey('Agent 신분 확인 완료 시각')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_level',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum')], db_index=True, default='BRONZE', help_text=translations.utils.DisplayKey('Bronze/Silver/Gold/Diamond/Platinum 레벨'), max_length=20, verbose_name=translations.utils.DisplayKey('Agent 레벨')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_level_constraints',
            field=models.JSONField(blank=True, default=dict, help_text=translations.utils.DisplayKey('향후 레벨별 제약 룰을 저장하기 위한 구조화 필드'), verbose_name=translations.utils.DisplayKey('레벨 기반 제약(초안)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_level_last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=translations.utils.DisplayKey('레벨 평가 시각')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_level_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=translations.utils.DisplayKey('완료건수/별점/수락률 기반 계산 점수(0~100 권장)'), max_digits=6, null=True, verbose_name=translations.utils.DisplayKey('Agent 레벨 점수')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_rating_avg_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=translations.utils.DisplayKey('레벨 계산 시점 기준 평균 별점(1~5)'), max_digits=4, null=True, verbose_name=translations.utils.DisplayKey('평점 평균(스냅샷)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_services',
            field=models.JSONField(blank=True, default=list, help_text=translations.utils.DisplayKey('에이전트 가입 시 선택한 SettlementService ID 목록'), verbose_name=translations.utils.DisplayKey('에이전트 서비스 (가입 시 선택)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_states',
            field=models.JSONField(blank=True, default=list, help_text=translations.utils.DisplayKey('에이전트가 커버하는 주 코드 목록 (예: NC, CA, TX)'), verbose_name=translations.utils.DisplayKey('커버 주(State)')),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name=translations.utils.DisplayKey('생년월일')),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=2, null=True, verbose_name=translations.utils.DisplayKey('성별')),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name=translations.utils.DisplayKey('휴대폰 번호')),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('ko', 'KR 한국어'), ('en', 'EN English'), ('es', 'ES Español'), ('zh-hans', 'ZH 中文(简体)'), ('zh-hant', 'ZH 中文(繁體)'), ('vi', 'VI Tiếng Việt')], default='en', max_length=10, verbose_name=translations.utils.DisplayKey('선호 언어')),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile/%Y/%m/', verbose_name=translations.utils.DisplayKey('프로필 사진')),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', '슈퍼 관리자'), ('ADMIN', '관리자'), ('SUPERVISOR', '운영 관리자'), ('HQ_STAFF', '본사 스태프'), ('AGENT', '에이전트'), ('CUSTOMER', '고객')], default='CUSTOMER', max_length=20),
        ),
    ]
