# Generated by Django 5.2.11 on 2026-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('UNVERIFIED', '인증전'), ('ACTIVE', '활성'), ('PENDING', '대기'), ('SUSPENDED', '정지')], default='ACTIVE', max_length=20),
        ),
    ]
