# Generated by Django 6.0.2 on 2026-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_admin_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_services",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="에이전트 가입 시 선택한 SettlementService ID 목록",
                verbose_name="에이전트 서비스 (가입 시 선택)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "관리자"),
                    ("AGENT", "에이전트"),
                    ("CUSTOMER", "고객"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
