# Generated by Django 6.0.2 on 2026-02-20 10:51

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_add_agent_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentForRating",
            fields=[],
            options={
                "verbose_name": "에이전트별 별점",
                "verbose_name_plural": "에이전트별 별점",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
