# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_agentforrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accept_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="에이전트 전체 약속 수락률. 예: 0.85 = 85%. 비워두면 서비스별 통계에서 계산해 표시.",
                max_digits=5,
                null=True,
                verbose_name="Accept rate (수락률)",
            ),
        ),
    ]
