# Generated by Django 6.0.2 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_accept_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ko", "KR 한국어"),
                    ("en", "EN English"),
                    ("zh-hans", "ZH 中文(简体)"),
                    ("zh-hant", "ZH 中文(繁體)"),
                    ("vi", "VI Tiếng Việt"),
                    ("es", "ES Español"),
                ],
                default="ko",
                max_length=10,
                verbose_name="선호 언어",
            ),
        ),
    ]
