# Generated by Django 6.0.2 on 2026-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settlementquoterequest",
            name="phone",
        ),
        migrations.AddField(
            model_name="settlementquoterequest",
            name="service_schedule",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='날짜별 서비스: {"YYYY-MM-DD": ["SERVICE_CODE", ...]}',
                verbose_name="서비스 일정",
            ),
        ),
    ]
