# Generated by Django 6.0.2 on 2026-02-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0002_remove_phone_add_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="항목이름")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("주거/임대", "주거/임대"),
                            ("교통/차량", "교통/차량"),
                            ("생활편의", "생활편의"),
                            ("의료/교육", "의료/교육"),
                            ("행정/문서", "행정/문서"),
                            ("기타", "기타"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "required_time",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="예: 60 = 1시간",
                        verbose_name="필요 시간(분)",
                    ),
                ),
                (
                    "customer_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Customer 가격",
                    ),
                ),
                (
                    "agent_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Agent 가격",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "서비스 항목",
                "verbose_name_plural": "서비스 항목",
                "ordering": ["category", "ordering", "name"],
            },
        ),
    ]
