# Generated by Django 6.0.2 on 2026-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0006_add_service_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementquoterequest",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="도시"),
        ),
        migrations.AddField(
            model_name="settlementquoterequest",
            name="entry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="입국/이주 예정일"
            ),
        ),
        migrations.AddField(
            model_name="settlementquoterequest",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="이주 State"
            ),
        ),
    ]
