# Generated by Django 6.0.2 on 2026-02-20 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0007_add_relocation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAppointmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_code",
                    models.CharField(max_length=50, verbose_name="서비스 코드"),
                ),
                ("service_date", models.DateField(verbose_name="희망 일자")),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="희망 시간대"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="메시지")),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연락처 이름"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="연락처 이메일"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("CONFIRMED", "확정"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "약속 신청",
                "verbose_name_plural": "약속 신청",
                "ordering": ["-created_at"],
            },
        ),
    ]
