# Generated by Django 6.0.2 on 2026-02-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0009_add_user_settlement_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementquoterequest",
            name="checkout_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="서비스 customer_price 합계",
                max_digits=14,
                verbose_name="Checkout 합계",
            ),
        ),
        migrations.AddField(
            model_name="usersettlementplan",
            name="checkout_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="서비스 customer_price 합계",
                max_digits=14,
                verbose_name="Checkout 합계",
            ),
        ),
    ]
