# Generated by Django 6.0.2 on 2026-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0011_agentappointmentrequest_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentappointmentrequest",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="24시간 미수락 시 에이전트에게 보낸 독촉 메시지 발송 시각",
                null=True,
                verbose_name="수락 독촉 알림 발송 시각",
            ),
        ),
    ]
