# Generated by Django 5.2.12 on 2026-03-15 11:34

import django.db.models.deletion
import translations.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0037_servicecompletionform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlementquoterequest',
            options={'ordering': ['-created_at'], 'verbose_name': translations.utils.DisplayKey('견적 신청'), 'verbose_name_plural': translations.utils.DisplayKey('견적 신청')},
        ),
        migrations.AlterModelOptions(
            name='settlementservice',
            options={'ordering': ['category', 'name'], 'verbose_name': translations.utils.DisplayKey('서비스 항목'), 'verbose_name_plural': translations.utils.DisplayKey('서비스 항목')},
        ),
        migrations.AlterModelOptions(
            name='usersettlementplan',
            options={'verbose_name': translations.utils.DisplayKey('사용자 정착 플랜'), 'verbose_name_plural': translations.utils.DisplayKey('사용자 정착 플랜')},
        ),
        migrations.RenameIndex(
            model_name='availabilityrequest',
            new_name='settlement__submiss_de3440_idx',
            old_name='settlement_a_submiss_66680f_idx',
        ),
        migrations.RenameIndex(
            model_name='availabilityrequest',
            new_name='settlement__target__627038_idx',
            old_name='settlement_a_target__64d1a2_idx',
        ),
        migrations.RenameIndex(
            model_name='casedocument',
            new_name='settlement__submiss_c91e4b_idx',
            old_name='settlement_c_submiss_983819_idx',
        ),
        migrations.RenameIndex(
            model_name='casedocument',
            new_name='settlement__submiss_e1e788_idx',
            old_name='settlement_c_submiss_4720ea_idx',
        ),
        migrations.RenameIndex(
            model_name='documentsignature',
            new_name='settlement__documen_54a1e6_idx',
            old_name='settlement_d_documen_62001b_idx',
        ),
        migrations.RenameIndex(
            model_name='documentsignature',
            new_name='settlement__signer__f67435_idx',
            old_name='settlement_d_signer__f92bdb_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecompletionform',
            new_name='settlement__submiss_d2e2da_idx',
            old_name='settlement_s_submiss_002f43_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecompletionform',
            new_name='settlement__agent_i_5b225d_idx',
            old_name='settlement_s_agent_i_761f57_idx',
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL, verbose_name=translations.utils.DisplayKey('Agent')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text=translations.utils.DisplayKey('취소 시 사유. 예: 사용자 취소, Agent 취소'), max_length=100, verbose_name=translations.utils.DisplayKey('취소 사유')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_requested', to=settings.AUTH_USER_MODEL, verbose_name=translations.utils.DisplayKey('신청자')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name=translations.utils.DisplayKey('연락처 이메일')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name=translations.utils.DisplayKey('연락처 이름')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name=translations.utils.DisplayKey('메시지')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, verbose_name=translations.utils.DisplayKey('희망 시간대')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text=translations.utils.DisplayKey('24시간 미수락 시 에이전트에게 보낸 독촉 메시지 발송 시각'), null=True, verbose_name=translations.utils.DisplayKey('수락 독촉 알림 발송 시각')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='service_code',
            field=models.CharField(max_length=50, verbose_name=translations.utils.DisplayKey('서비스 코드')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='service_date',
            field=models.DateField(verbose_name=translations.utils.DisplayKey('희망 일자')),
        ),
        migrations.AlterField(
            model_name='agentappointmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('CONFIRMED', '확정'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name=translations.utils.DisplayKey('상태')),
        ),
        migrations.AlterField(
            model_name='settlementquote',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='[{"code":"X","label":"서비스명","price":50000,"_auto":true,"_needs_review":false}, ...] _auto/_needs_review는 자동 생성 시 사용.', verbose_name='견적 항목'),
        ),
        migrations.AlterField(
            model_name='settlementquote',
            name='revision_superseded_at',
            field=models.DateTimeField(blank=True, help_text='설문 재개 승인 시 설정. 이 견적은 결제 대상에서 제외(무효화). 레코드는 삭제하지 않음.', null=True, verbose_name='수정 요청으로 대체 시각'),
        ),
        migrations.AlterField(
            model_name='settlementquote',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='재제출·재견적 흐름에서 이 견적이 대체한 이전 견적. Admin에서 이전/새 견적 관계 추적용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_quotes', to='settlement.settlementquote', verbose_name='대체한 견적'),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='ai_suggested',
            field=models.BooleanField(default=False, verbose_name=translations.utils.DisplayKey('AI 추천 사용')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='checkout_total',
            field=models.DecimalField(decimal_places=0, default=0, help_text=translations.utils.DisplayKey('서비스 customer_price 합계'), max_digits=14, verbose_name=translations.utils.DisplayKey('Checkout 합계')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name=translations.utils.DisplayKey('도시')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=translations.utils.DisplayKey('이메일')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name=translations.utils.DisplayKey('입국/이주 예정일')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='memo',
            field=models.TextField(blank=True, verbose_name=translations.utils.DisplayKey('추가 문의사항')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name=translations.utils.DisplayKey('이름')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='service_schedule',
            field=models.JSONField(blank=True, default=dict, help_text=translations.utils.DisplayKey('날짜별 서비스: {"YYYY-MM-DD": ["SERVICE_CODE", ...]}'), verbose_name=translations.utils.DisplayKey('서비스 일정')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='services',
            field=models.JSONField(default=list, verbose_name=translations.utils.DisplayKey('선택 서비스')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name=translations.utils.DisplayKey('이주 State')),
        ),
        migrations.AlterField(
            model_name='settlementquoterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_quotes', to=settings.AUTH_USER_MODEL, verbose_name=translations.utils.DisplayKey('신청자')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='agent_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name=translations.utils.DisplayKey('Agent 가격')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='category',
            field=models.CharField(choices=[('주거/임대', '주거/임대'), ('교통/차량', '교통/차량'), ('생활편의', '생활편의'), ('의료/교육', '의료/교육'), ('행정/문서', '행정/문서'), ('기타', '기타')], max_length=20, verbose_name=translations.utils.DisplayKey('카테고리')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='code',
            field=models.CharField(blank=True, help_text=translations.utils.DisplayKey('견적/스케줄 식별용 (예: DRIVERS_LICENSE). 비어있으면 id 사용'), max_length=50, null=True, unique=True, verbose_name=translations.utils.DisplayKey('서비스 코드')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='customer_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name=translations.utils.DisplayKey('Customer 가격')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=translations.utils.DisplayKey('활성')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name=translations.utils.DisplayKey('항목이름')),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='required_time',
            field=models.PositiveIntegerField(default=60, help_text=translations.utils.DisplayKey('예: 60 = 1시간'), verbose_name=translations.utils.DisplayKey('필요 시간(분)')),
        ),
        migrations.AlterField(
            model_name='usersettlementplan',
            name='checkout_total',
            field=models.DecimalField(decimal_places=0, default=0, help_text=translations.utils.DisplayKey('서비스 customer_price 합계'), max_digits=14, verbose_name=translations.utils.DisplayKey('Checkout 합계')),
        ),
        migrations.AlterField(
            model_name='usersettlementplan',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name=translations.utils.DisplayKey('도시')),
        ),
        migrations.AlterField(
            model_name='usersettlementplan',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name=translations.utils.DisplayKey('입국/이주 예정일')),
        ),
        migrations.AlterField(
            model_name='usersettlementplan',
            name='service_schedule',
            field=models.JSONField(blank=True, default=dict, help_text=translations.utils.DisplayKey('{"YYYY-MM-DD": [{"code":"X","label":"Y"}, ...]}'), verbose_name=translations.utils.DisplayKey('서비스 일정')),
        ),
        migrations.AlterField(
            model_name='usersettlementplan',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name=translations.utils.DisplayKey('이주 State')),
        ),
        migrations.AlterField(
            model_name='usersettlementplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_plan', to=settings.AUTH_USER_MODEL, verbose_name=translations.utils.DisplayKey('사용자')),
        ),
    ]
