# Generated by Django 6.0.2 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversation_survey_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('APPOINTMENT', '약속 대화'), ('NOTICE', '공지'), ('AI_ASSISTANT', 'AI 어시스턴트')], default='APPOINTMENT', max_length=20),
        ),
    ]
