# Generated by Django 6.0.2 on 2026-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_add_request_id_to_intent_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrequestintentanalysis",
            name="route_candidates",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="top-k 후보(merged_candidates), selected_primary_page, recommendation_confidence. 학습·ranking용.",
                verbose_name="경로 추천 후보",
            ),
        ),
    ]
