# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0010_add_route_candidates_to_intent_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRequestLearningSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="요청 흐름 ID")),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="user_message, predicted_primary_page, actual_edit_page, label_quality, positive_labels, negative_labels 등.",
                        verbose_name="학습 요약",
                    ),
                ),
                (
                    "label_quality",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="strong | medium | weak",
                        max_length=16,
                        verbose_name="라벨 품질",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "요청 학습 요약",
                "verbose_name_plural": "요청 학습 요약",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customerrequestlearningsummary",
            index=models.Index(fields=["label_quality"], name="messaging_c_label_q_8e0e0d_idx"),
        ),
    ]
