# Generated by Django 6.0.2 on 2026-03-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="표시 순서"),
                ),
                ("step", models.PositiveIntegerField(default=1, verbose_name="단계")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="키"),
                ),
                ("label", models.CharField(max_length=300, verbose_name="라벨")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("textarea", "긴 텍스트"),
                            ("select", "선택(단일)"),
                            ("radio", "라디오"),
                            ("checkbox", "체크박스(다중)"),
                            ("number", "숫자"),
                            ("date", "날짜"),
                            ("email", "이메일"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="필드 타입",
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="필수")),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='select/radio/checkbox 시 [{"value":"x","label":"X"}, ...]',
                        verbose_name="선택지",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(blank=True, max_length=500, verbose_name="도움말"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
            ],
            options={
                "verbose_name": "설문 문항",
                "verbose_name_plural": "설문 문항",
                "ordering": ["step", "order"],
            },
        ),
        migrations.CreateModel(
            name="SurveySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "초안"), ("SUBMITTED", "제출 완료")],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(default=1, verbose_name="현재 단계"),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="key -> value. DRAFT 시 일부만 있어도 저장 가능.",
                        verbose_name="답변",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 저장 시각"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="제출 시각"
                    ),
                ),
                (
                    "preferred_support_mode",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="선호 지원 방식"
                    ),
                ),
                (
                    "requested_required_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="서비스 코드 목록",
                        verbose_name="필수 요청 서비스",
                    ),
                ),
                (
                    "requested_optional_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="서비스 코드 목록",
                        verbose_name="선택 요청 서비스",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "설문 제출",
                "verbose_name_plural": "설문 제출",
                "ordering": ["-updated_at"],
            },
        ),
    ]
