# Generated by Django 6.0.2 on 2026-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_move_main_visa_holder_to_entry_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['step', 'order_in_section', 'order'], 'verbose_name': '설문 문항', 'verbose_name_plural': '설문 문항'},
        ),
        migrations.AlterModelOptions(
            name='surveysection',
            options={'ordering': ['display_order', 'id'], 'verbose_name': '설문', 'verbose_name_plural': '설문'},
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('DRAFT', '고객 설문 작성중'), ('SUBMITTED', 'Admin 검토중'), ('REVISION_REQUESTED', '고객 수정 요청됨'), ('AWAITING_PAYMENT', '고객 결재 대기중'), ('AGENT_ASSIGNMENT', 'Agent 할당 중'), ('SERVICE_IN_PROGRESS', '서비스 진행중')], db_index=True, default='DRAFT', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='surveysubmissionevent',
            name='event_type',
            field=models.CharField(choices=[('submitted', '제출'), ('revision_requested', '수정 요청'), ('sections_update_requested', '카드별 수정 요청'), ('resubmitted', '재제출'), ('quote_sent', '견적 송부'), ('paid', '결제 완료')], max_length=30, verbose_name='이벤트'),
        ),
    ]
