# Generated by Django 6.0.2 on 2026-03-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_schedule_domain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmissionevent',
            name='event_type',
            field=models.CharField(choices=[('submitted', '제출'), ('revision_requested', '수정 요청'), ('sections_update_requested', '카드별 수정 요청'), ('resubmitted', '재제출'), ('quote_sent', '견적 송부'), ('paid', '결제 완료'), ('schedule_sent', '일정 송부')], max_length=30, verbose_name='이벤트'),
        ),
    ]
