# Generated by Django 5.2.11 on 2026-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaticTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="템플릿에서 사용하는 문구(예: 로그아웃, 내 정착 플랜)",
                        max_length=500,
                        verbose_name="원문(키)",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=20, verbose_name="언어"),
                ),
                ("value", models.CharField(max_length=1000, verbose_name="번역문")),
            ],
            options={
                "verbose_name": "고정 번역",
                "verbose_name_plural": "고정 번역",
                "ordering": ["language_code", "key"],
                "unique_together": {("key", "language_code")},
            },
        ),
    ]
