# Generated by Django 6.0.2 on 2026-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial_survey_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysubmission",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="24시간마다 DRAFT 미제출자에게 리마인드 이메일 발송 시 갱신. 하루 1회 제한.",
                null=True,
                verbose_name="마지막 리마인드 발송 시각",
            ),
        ),
    ]
