# Generated by Django 5.2.11 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_provider_to_agent_in_allowed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='부제목')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='표시')),
                ('background_type', models.CharField(choices=[('IMAGE', '이미지'), ('GRADIENT', '그라데이션')], default='GRADIENT', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name='배경 이미지')),
                ('gradient_css', models.CharField(blank=True, help_text='예: linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%)', max_length=200, verbose_name='그라데이션 CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '캐러셀 슬라이드',
                'verbose_name_plural': '캐러셀 슬라이드',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-updated_at',), 'verbose_name': '컨텐츠', 'verbose_name_plural': '컨텐츠'},
        ),
        migrations.AlterField(
            model_name='content',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='접근 허용 역할 (GUEST=비로그인, CUSTOMER, AGENT, ADMIN)'),
        ),
    ]
