# Generated by Django 5.2.11 on 2026-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_seed_carousel_slides"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCarouselSlide",
            fields=[],
            options={
                "verbose_name": "캐러셀 (광고)",
                "verbose_name_plural": "캐러셀 (광고)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.carouselslide",),
        ),
        migrations.CreateModel(
            name="CorporateCarouselSlide",
            fields=[],
            options={
                "verbose_name": "캐러셀 (기업서비스)",
                "verbose_name_plural": "캐러셀 (기업서비스)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.carouselslide",),
        ),
        migrations.CreateModel(
            name="HomeIntroSlide",
            fields=[],
            options={
                "verbose_name": "캐러셀 (홈인트로)",
                "verbose_name_plural": "캐러셀 (홈인트로)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.carouselslide",),
        ),
        migrations.CreateModel(
            name="SettlementCarouselSlide",
            fields=[],
            options={
                "verbose_name": "캐러셀 (정착서비스)",
                "verbose_name_plural": "캐러셀 (정착서비스)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.carouselslide",),
        ),
        migrations.AlterModelOptions(
            name="carouselslide",
            options={
                "ordering": ["placement", "order", "id"],
                "verbose_name": "캐러셀 슬라이드",
                "verbose_name_plural": "캐러셀 슬라이드",
            },
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="광고 등 클릭 시 이동할 URL",
                verbose_name="링크 URL",
            ),
        ),
        migrations.AddField(
            model_name="carouselslide",
            name="placement",
            field=models.CharField(
                choices=[
                    ("HOME_INTRO", "홈인트로"),
                    ("SETTLEMENT", "정착서비스"),
                    ("CORPORATE", "기업서비스"),
                    ("AD", "광고"),
                ],
                db_index=True,
                default="HOME_INTRO",
                max_length=20,
                verbose_name="노출 위치",
            ),
        ),
        migrations.AlterField(
            model_name="carouselslide",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="정렬"),
        ),
    ]
