# Generated by Django 6.0.2 on 2026-02-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_seed_ad_carousel_slides"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAdRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="회사/업체명"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="담당자명"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="연락처"),
                ),
                (
                    "ad_title",
                    models.CharField(max_length=200, verbose_name="광고 제목"),
                ),
                (
                    "ad_subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="광고 부제목"
                    ),
                ),
                ("link_url", models.URLField(verbose_name="링크 URL")),
                ("memo", models.TextField(blank=True, verbose_name="추가 요청사항")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "검토 대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "광고 등록 신청",
                "verbose_name_plural": "광고 등록 신청",
                "ordering": ["-created_at"],
            },
        ),
    ]
