# 각 주(State)별 주요 도시 전체 추가 - NC 수준으로 모든 주 확장

from django.db import migrations

# (region_code, state_code, state_name, slug, city_name, order)
ALL_CITIES = [
    # === WEST ===
    # AZ - Arizona
    ('WEST', 'AZ', 'Arizona', 'az-tempe', 'Tempe', 6),
    ('WEST', 'AZ', 'Arizona', 'az-glendale', 'Glendale', 7),
    ('WEST', 'AZ', 'Arizona', 'az-gilbert', 'Gilbert', 8),
    ('WEST', 'AZ', 'Arizona', 'az-peoria', 'Peoria', 10),
    ('WEST', 'AZ', 'Arizona', 'az-surprise', 'Surprise', 11),
    ('WEST', 'AZ', 'Arizona', 'az-flagstaff', 'Flagstaff', 12),
    ('WEST', 'AZ', 'Arizona', 'az-yuma', 'Yuma', 13),
    ('WEST', 'AZ', 'Arizona', 'az-casa-grande', 'Casa Grande', 14),
    # CA - California (기존: SF, Sac, SJ, LA, Irvine, SD + 0003)
    ('WEST', 'CA', 'California', 'ca-modesto', 'Modesto', 18),
    ('WEST', 'CA', 'California', 'ca-fontana', 'Fontana', 19),
    ('WEST', 'CA', 'California', 'ca-oxnard', 'Oxnard', 20),
    ('WEST', 'CA', 'California', 'ca-moreno-valley', 'Moreno Valley', 21),
    ('WEST', 'CA', 'California', 'ca-huntington-beach', 'Huntington Beach', 22),
    ('WEST', 'CA', 'California', 'ca-glendale', 'Glendale', 23),
    ('WEST', 'CA', 'California', 'ca-santa-clarita', 'Santa Clarita', 24),
    ('WEST', 'CA', 'California', 'ca-garden-grove', 'Garden Grove', 25),
    ('WEST', 'CA', 'California', 'ca-ontario', 'Ontario', 26),
    ('WEST', 'CA', 'California', 'ca-rancho-cucamonga', 'Rancho Cucamonga', 27),
    ('WEST', 'CA', 'California', 'ca-santa-rosa', 'Santa Rosa', 28),
    ('WEST', 'CA', 'California', 'ca-elk-grove', 'Elk Grove', 29),
    ('WEST', 'CA', 'California', 'ca-corona', 'Corona', 30),
    ('WEST', 'CA', 'California', 'ca-lancaster', 'Lancaster', 31),
    ('WEST', 'CA', 'California', 'ca-palmdale', 'Palmdale', 32),
    ('WEST', 'CA', 'California', 'ca-salinas', 'Salinas', 33),
    ('WEST', 'CA', 'California', 'ca-pomona', 'Pomona', 34),
    ('WEST', 'CA', 'California', 'ca-hayward', 'Hayward', 35),
    ('WEST', 'CA', 'California', 'ca-escondido', 'Escondido', 36),
    ('WEST', 'CA', 'California', 'ca-torrance', 'Torrance', 37),
    ('WEST', 'CA', 'California', 'ca-pasadena', 'Pasadena', 38),
    ('WEST', 'CA', 'California', 'ca-orange', 'Orange', 39),
    ('WEST', 'CA', 'California', 'ca-fullerton', 'Fullerton', 40),
    # CO - Colorado
    ('WEST', 'CO', 'Colorado', 'co-aurora', 'Aurora', 4),
    ('WEST', 'CO', 'Colorado', 'co-fort-collins', 'Fort Collins', 5),
    ('WEST', 'CO', 'Colorado', 'co-lakewood', 'Lakewood', 6),
    ('WEST', 'CO', 'Colorado', 'co-thornton', 'Thornton', 7),
    ('WEST', 'CO', 'Colorado', 'co-arvada', 'Arvada', 8),
    ('WEST', 'CO', 'Colorado', 'co-westminster', 'Westminster', 9),
    ('WEST', 'CO', 'Colorado', 'co-pueblo', 'Pueblo', 10),
    ('WEST', 'CO', 'Colorado', 'co-centennial', 'Centennial', 11),
    ('WEST', 'CO', 'Colorado', 'co-greeley', 'Greeley', 12),
    ('WEST', 'CO', 'Colorado', 'co-longmont', 'Longmont', 13),
    # HI - Hawaii
    ('WEST', 'HI', 'Hawaii', 'hi-pearl-city', 'Pearl City', 2),
    ('WEST', 'HI', 'Hawaii', 'hi-hilo', 'Hilo', 3),
    ('WEST', 'HI', 'Hawaii', 'hi-kailua', 'Kailua', 4),
    ('WEST', 'HI', 'Hawaii', 'hi-waipahu', 'Waipahu', 5),
    ('WEST', 'HI', 'Hawaii', 'hi-mililani', 'Mililani', 6),
    ('WEST', 'HI', 'Hawaii', 'hi-kaneohe', 'Kaneohe', 7),
    ('WEST', 'HI', 'Hawaii', 'hi-ewa-beach', 'Ewa Beach', 8),
    ('WEST', 'HI', 'Hawaii', 'hi-mililani-mauka', 'Mililani Mauka', 9),
    ('WEST', 'HI', 'Hawaii', 'hi-kihei', 'Kihei', 10),
    # NV - Nevada
    ('WEST', 'NV', 'Nevada', 'nv-henderson', 'Henderson', 3),
    ('WEST', 'NV', 'Nevada', 'nv-paradise', 'Paradise', 4),
    ('WEST', 'NV', 'Nevada', 'nv-north-las-vegas', 'North Las Vegas', 5),
    ('WEST', 'NV', 'Nevada', 'nv-sparks', 'Sparks', 6),
    ('WEST', 'NV', 'Nevada', 'nv-carson-city', 'Carson City', 7),
    ('WEST', 'NV', 'Nevada', 'nv-spring-valley', 'Spring Valley', 8),
    ('WEST', 'NV', 'Nevada', 'nv-summerlin', 'Summerlin', 9),
    # OR - Oregon
    ('WEST', 'OR', 'Oregon', 'or-gresham', 'Gresham', 4),
    ('WEST', 'OR', 'Oregon', 'or-beaverton', 'Beaverton', 5),
    ('WEST', 'OR', 'Oregon', 'or-bend', 'Bend', 6),
    ('WEST', 'OR', 'Oregon', 'or-medford', 'Medford', 7),
    ('WEST', 'OR', 'Oregon', 'or-springfield', 'Springfield', 8),
    ('WEST', 'OR', 'Oregon', 'or-corvallis', 'Corvallis', 9),
    ('WEST', 'OR', 'Oregon', 'or-tigard', 'Tigard', 10),
    ('WEST', 'OR', 'Oregon', 'or-lake-oswego', 'Lake Oswego', 11),
    ('WEST', 'OR', 'Oregon', 'or-keizer', 'Keizer', 12),
    # UT - Utah
    ('WEST', 'UT', 'Utah', 'ut-west-valley-city', 'West Valley City', 2),
    ('WEST', 'UT', 'Utah', 'ut-provo', 'Provo', 3),
    ('WEST', 'UT', 'Utah', 'ut-west-jordan', 'West Jordan', 4),
    ('WEST', 'UT', 'Utah', 'ut-orem', 'Orem', 5),
    ('WEST', 'UT', 'Utah', 'ut-sandy', 'Sandy', 6),
    ('WEST', 'UT', 'Utah', 'ut-ogden', 'Ogden', 7),
    ('WEST', 'UT', 'Utah', 'ut-st-george', 'St. George', 8),
    ('WEST', 'UT', 'Utah', 'ut-layton', 'Layton', 9),
    ('WEST', 'UT', 'Utah', 'ut-taylorsville', 'Taylorsville', 10),
    ('WEST', 'UT', 'Utah', 'ut-south-jordan', 'South Jordan', 11),
    # WA - Washington
    ('WEST', 'WA', 'Washington', 'wa-bellevue', 'Bellevue', 5),
    ('WEST', 'WA', 'Washington', 'wa-kent', 'Kent', 6),
    ('WEST', 'WA', 'Washington', 'wa-everett', 'Everett', 7),
    ('WEST', 'WA', 'Washington', 'wa-renton', 'Renton', 8),
    ('WEST', 'WA', 'Washington', 'wa-federal-way', 'Federal Way', 9),
    ('WEST', 'WA', 'Washington', 'wa-yakima', 'Yakima', 10),
    ('WEST', 'WA', 'Washington', 'wa-bellingham', 'Bellingham', 11),
    ('WEST', 'WA', 'Washington', 'wa-kirkland', 'Kirkland', 12),
    ('WEST', 'WA', 'Washington', 'wa-kennewick', 'Kennewick', 13),
    ('WEST', 'WA', 'Washington', 'wa-auburn', 'Auburn', 14),
    ('WEST', 'WA', 'Washington', 'wa-pasco', 'Pasco', 15),
    ('WEST', 'WA', 'Washington', 'wa-marysville', 'Marysville', 16),
    # === CENTRAL ===
    # IL - Illinois
    ('CENTRAL', 'IL', 'Illinois', 'il-peoria', 'Peoria', 7),
    ('CENTRAL', 'IL', 'Illinois', 'il-springfield', 'Springfield', 8),
    ('CENTRAL', 'IL', 'Illinois', 'il-elgin', 'Elgin', 9),
    ('CENTRAL', 'IL', 'Illinois', 'il-waukegan', 'Waukegan', 10),
    ('CENTRAL', 'IL', 'Illinois', 'il-cicero', 'Cicero', 11),
    ('CENTRAL', 'IL', 'Illinois', 'il-bloomington', 'Bloomington', 12),
    ('CENTRAL', 'IL', 'Illinois', 'il-arlington-heights', 'Arlington Heights', 13),
    ('CENTRAL', 'IL', 'Illinois', 'il-evanston', 'Evanston', 14),
    ('CENTRAL', 'IL', 'Illinois', 'il-schaumburg', 'Schaumburg', 15),
    ('CENTRAL', 'IL', 'Illinois', 'il-bolingbrook', 'Bolingbrook', 16),
    ('CENTRAL', 'IL', 'Illinois', 'il-palatine', 'Palatine', 17),
    # KS - Kansas
    ('CENTRAL', 'KS', 'Kansas', 'ks-wichita', 'Wichita', 2),
    ('CENTRAL', 'KS', 'Kansas', 'ks-overland-park', 'Overland Park', 3),
    ('CENTRAL', 'KS', 'Kansas', 'ks-olathe', 'Olathe', 4),
    ('CENTRAL', 'KS', 'Kansas', 'ks-lawrence', 'Lawrence', 5),
    ('CENTRAL', 'KS', 'Kansas', 'ks-topeka', 'Topeka', 6),
    ('CENTRAL', 'KS', 'Kansas', 'ks-lenexa', 'Lenexa', 7),
    ('CENTRAL', 'KS', 'Kansas', 'ks-shawnee', 'Shawnee', 8),
    ('CENTRAL', 'KS', 'Kansas', 'ks-manhattan', 'Manhattan', 9),
    # KY - Kentucky
    ('CENTRAL', 'KY', 'Kentucky', 'ky-lexington', 'Lexington', 2),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-bowling-green', 'Bowling Green', 3),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-owensboro', 'Owensboro', 4),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-covington', 'Covington', 5),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-richmond', 'Richmond', 6),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-georgetown', 'Georgetown', 7),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-florence', 'Florence', 8),
    ('CENTRAL', 'KY', 'Kentucky', 'ky-elizabethtown', 'Elizabethtown', 9),
    # MI - Michigan
    ('CENTRAL', 'MI', 'Michigan', 'mi-grand-rapids', 'Grand Rapids', 2),
    ('CENTRAL', 'MI', 'Michigan', 'mi-warren', 'Warren', 3),
    ('CENTRAL', 'MI', 'Michigan', 'mi-ann-arbor', 'Ann Arbor', 4),
    ('CENTRAL', 'MI', 'Michigan', 'mi-lansing', 'Lansing', 5),
    ('CENTRAL', 'MI', 'Michigan', 'mi-flint', 'Flint', 6),
    ('CENTRAL', 'MI', 'Michigan', 'mi-dearborn', 'Dearborn', 7),
    ('CENTRAL', 'MI', 'Michigan', 'mi-livonia', 'Livonia', 8),
    ('CENTRAL', 'MI', 'Michigan', 'mi-troy', 'Troy', 9),
    ('CENTRAL', 'MI', 'Michigan', 'mi-westland', 'Westland', 10),
    ('CENTRAL', 'MI', 'Michigan', 'mi-farmington-hills', 'Farmington Hills', 11),
    # MN - Minnesota
    ('CENTRAL', 'MN', 'Minnesota', 'mn-saint-paul', 'Saint Paul', 2),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-rochester', 'Rochester', 3),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-duluth', 'Duluth', 4),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-bloomington', 'Bloomington', 5),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-brooklyn-park', 'Brooklyn Park', 6),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-plymouth', 'Plymouth', 7),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-woodbury', 'Woodbury', 8),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-lakeville', 'Lakeville', 9),
    ('CENTRAL', 'MN', 'Minnesota', 'mn-maple-grove', 'Maple Grove', 10),
    # MO - Missouri
    ('CENTRAL', 'MO', 'Missouri', 'mo-kansas-city', 'Kansas City', 2),
    ('CENTRAL', 'MO', 'Missouri', 'mo-springfield', 'Springfield', 3),
    ('CENTRAL', 'MO', 'Missouri', 'mo-columbia', 'Columbia', 4),
    ('CENTRAL', 'MO', 'Missouri', 'mo-independence', 'Independence', 5),
    ('CENTRAL', 'MO', 'Missouri', 'mo-lees-summit', "Lee's Summit", 6),
    ('CENTRAL', 'MO', 'Missouri', 'mo-o-fallon', "O'Fallon", 7),
    ('CENTRAL', 'MO', 'Missouri', 'mo-saint-joseph', 'Saint Joseph', 8),
    ('CENTRAL', 'MO', 'Missouri', 'mo-saint-charles', 'Saint Charles', 9),
    # NE - Nebraska
    ('CENTRAL', 'NE', 'Nebraska', 'ne-lincoln', 'Lincoln', 2),
    ('CENTRAL', 'NE', 'Nebraska', 'ne-bellevue', 'Bellevue', 3),
    ('CENTRAL', 'NE', 'Nebraska', 'ne-grand-island', 'Grand Island', 4),
    ('CENTRAL', 'NE', 'Nebraska', 'ne-kearney', 'Kearney', 5),
    ('CENTRAL', 'NE', 'Nebraska', 'ne-fremont', 'Fremont', 6),
    # OH - Ohio
    ('CENTRAL', 'OH', 'Ohio', 'oh-dayton', 'Dayton', 6),
    ('CENTRAL', 'OH', 'Ohio', 'oh-canton', 'Canton', 7),
    ('CENTRAL', 'OH', 'Ohio', 'oh-parma', 'Parma', 8),
    ('CENTRAL', 'OH', 'Ohio', 'oh-lorain', 'Lorain', 9),
    ('CENTRAL', 'OH', 'Ohio', 'oh-hamilton', 'Hamilton', 10),
    ('CENTRAL', 'OH', 'Ohio', 'oh-youngstown', 'Youngstown', 11),
    ('CENTRAL', 'OH', 'Ohio', 'oh-mansfield', 'Mansfield', 12),
    ('CENTRAL', 'OH', 'Ohio', 'oh-newark', 'Newark', 13),
    ('CENTRAL', 'OH', 'Ohio', 'oh-dublin', 'Dublin', 14),
    ('CENTRAL', 'OH', 'Ohio', 'oh-beavercreek', 'Beavercreek', 15),
    # OK - Oklahoma
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-tulsa', 'Tulsa', 2),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-norman', 'Norman', 3),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-broken-arrow', 'Broken Arrow', 4),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-lawton', 'Lawton', 5),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-edmond', 'Edmond', 6),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-moore', 'Moore', 7),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-midwest-city', 'Midwest City', 8),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-enid', 'Enid', 9),
    ('CENTRAL', 'OK', 'Oklahoma', 'ok-stillwater', 'Stillwater', 10),
    # TN - Tennessee
    ('CENTRAL', 'TN', 'Tennessee', 'tn-knoxville', 'Knoxville', 2),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-chattanooga', 'Chattanooga', 3),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-clarksville', 'Clarksville', 4),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-murfreesboro', 'Murfreesboro', 5),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-franklin', 'Franklin', 6),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-jackson', 'Jackson', 7),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-johnson-city', 'Johnson City', 8),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-bartlett', 'Bartlett', 9),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-germantown', 'Germantown', 10),
    ('CENTRAL', 'TN', 'Tennessee', 'tn-collierville', 'Collierville', 11),
    # TX - Texas (기존: dallas + 0003)
    ('CENTRAL', 'TX', 'Texas', 'tx-irving', 'Irving', 11),
    ('CENTRAL', 'TX', 'Texas', 'tx-frisco', 'Frisco', 12),
    ('CENTRAL', 'TX', 'Texas', 'tx-mckinney', 'McKinney', 13),
    ('CENTRAL', 'TX', 'Texas', 'tx-grand-prairie', 'Grand Prairie', 14),
    ('CENTRAL', 'TX', 'Texas', 'tx-mcallen', 'McAllen', 15),
    ('CENTRAL', 'TX', 'Texas', 'tx-waco', 'Waco', 16),
    ('CENTRAL', 'TX', 'Texas', 'tx-killeen', 'Killeen', 17),
    ('CENTRAL', 'TX', 'Texas', 'tx-denton', 'Denton', 18),
    ('CENTRAL', 'TX', 'Texas', 'tx-midland', 'Midland', 19),
    ('CENTRAL', 'TX', 'Texas', 'tx-abilene', 'Abilene', 20),
    ('CENTRAL', 'TX', 'Texas', 'tx-beaumont', 'Beaumont', 21),
    ('CENTRAL', 'TX', 'Texas', 'tx-round-rock', 'Round Rock', 22),
    ('CENTRAL', 'TX', 'Texas', 'tx-odessa', 'Odessa', 23),
    ('CENTRAL', 'TX', 'Texas', 'tx-wichita-falls', 'Wichita Falls', 24),
    ('CENTRAL', 'TX', 'Texas', 'tx-richardson', 'Richardson', 25),
    # === EAST ===
    # CT - Connecticut
    ('EAST', 'CT', 'Connecticut', 'ct-stamford', 'Stamford', 2),
    ('EAST', 'CT', 'Connecticut', 'ct-hartford', 'Hartford', 3),
    ('EAST', 'CT', 'Connecticut', 'ct-norwalk', 'Norwalk', 4),
    ('EAST', 'CT', 'Connecticut', 'ct-danbury', 'Danbury', 5),
    ('EAST', 'CT', 'Connecticut', 'ct-bristol', 'Bristol', 6),
    ('EAST', 'CT', 'Connecticut', 'ct-meriden', 'Meriden', 7),
    ('EAST', 'CT', 'Connecticut', 'ct-west-haven', 'West Haven', 8),
    ('EAST', 'CT', 'Connecticut', 'ct-milford', 'Milford', 9),
    # FL - Florida (기존: miami, orlando, tampa, jacksonville-gainesville + 0003)
    ('EAST', 'FL', 'Florida', 'fl-hialeah', 'Hialeah', 12),
    ('EAST', 'FL', 'Florida', 'fl-port-st-lucie', 'Port St. Lucie', 13),
    ('EAST', 'FL', 'Florida', 'fl-pembroke-pines', 'Pembroke Pines', 15),
    ('EAST', 'FL', 'Florida', 'fl-hollywood', 'Hollywood', 16),
    ('EAST', 'FL', 'Florida', 'fl-miami-gardens', 'Miami Gardens', 17),
    ('EAST', 'FL', 'Florida', 'fl-gainesville', 'Gainesville', 18),
    ('EAST', 'FL', 'Florida', 'fl-coral-springs', 'Coral Springs', 19),
    ('EAST', 'FL', 'Florida', 'fl-palm-bay', 'Palm Bay', 20),
    ('EAST', 'FL', 'Florida', 'fl-clearwater', 'Clearwater', 21),
    ('EAST', 'FL', 'Florida', 'fl-pompano-beach', 'Pompano Beach', 22),
    ('EAST', 'FL', 'Florida', 'fl-west-palm-beach', 'West Palm Beach', 23),
    ('EAST', 'FL', 'Florida', 'fl-lakeland', 'Lakeland', 24),
    ('EAST', 'FL', 'Florida', 'fl-deltona', 'Deltona', 25),
    ('EAST', 'FL', 'Florida', 'fl-plant-city', 'Plant City', 26),
    # GA - Georgia (기존: atlanta, savannah + 0003)
    ('EAST', 'GA', 'Georgia', 'ga-athens', 'Athens', 6),
    ('EAST', 'GA', 'Georgia', 'ga-sandy-springs', 'Sandy Springs', 7),
    ('EAST', 'GA', 'Georgia', 'ga-south-fulton', 'South Fulton', 8),
    ('EAST', 'GA', 'Georgia', 'ga-roswell', 'Roswell', 9),
    ('EAST', 'GA', 'Georgia', 'ga-johns-creek', 'Johns Creek', 10),
    ('EAST', 'GA', 'Georgia', 'ga-alpharetta', 'Alpharetta', 11),
    ('EAST', 'GA', 'Georgia', 'ga-marietta', 'Marietta', 12),
    ('EAST', 'GA', 'Georgia', 'ga-warner-robins', 'Warner Robins', 13),
    ('EAST', 'GA', 'Georgia', 'ga-albany', 'Albany', 14),
    ('EAST', 'GA', 'Georgia', 'ga-valdosta', 'Valdosta', 15),
    # IN - Indiana
    ('EAST', 'IN', 'Indiana', 'in-fort-wayne', 'Fort Wayne', 2),
    ('EAST', 'IN', 'Indiana', 'in-evansville', 'Evansville', 3),
    ('EAST', 'IN', 'Indiana', 'in-south-bend', 'South Bend', 4),
    ('EAST', 'IN', 'Indiana', 'in-carmel', 'Carmel', 5),
    ('EAST', 'IN', 'Indiana', 'in-bloomington', 'Bloomington', 6),
    ('EAST', 'IN', 'Indiana', 'in-fishers', 'Fishers', 7),
    ('EAST', 'IN', 'Indiana', 'in-hammond', 'Hammond', 8),
    ('EAST', 'IN', 'Indiana', 'in-gary', 'Gary', 9),
    ('EAST', 'IN', 'Indiana', 'in-lafayette', 'Lafayette', 10),
    # MA - Massachusetts
    ('EAST', 'MA', 'Massachusetts', 'ma-worcester', 'Worcester', 2),
    ('EAST', 'MA', 'Massachusetts', 'ma-springfield', 'Springfield', 3),
    ('EAST', 'MA', 'Massachusetts', 'ma-cambridge', 'Cambridge', 4),
    ('EAST', 'MA', 'Massachusetts', 'ma-lowell', 'Lowell', 5),
    ('EAST', 'MA', 'Massachusetts', 'ma-brockton', 'Brockton', 6),
    ('EAST', 'MA', 'Massachusetts', 'ma-quincy', 'Quincy', 7),
    ('EAST', 'MA', 'Massachusetts', 'ma-lynn', 'Lynn', 8),
    ('EAST', 'MA', 'Massachusetts', 'ma-new-bedford', 'New Bedford', 9),
    ('EAST', 'MA', 'Massachusetts', 'ma-fall-river', 'Fall River', 10),
    ('EAST', 'MA', 'Massachusetts', 'ma-salem', 'Salem', 11),
    # MD - Maryland
    ('EAST', 'MD', 'Maryland', 'md-frederick', 'Frederick', 2),
    ('EAST', 'MD', 'Maryland', 'md-rockville', 'Rockville', 3),
    ('EAST', 'MD', 'Maryland', 'md-gaithersburg', 'Gaithersburg', 4),
    ('EAST', 'MD', 'Maryland', 'md-bowie', 'Bowie', 5),
    ('EAST', 'MD', 'Maryland', 'md-hagerstown', 'Hagerstown', 6),
    ('EAST', 'MD', 'Maryland', 'md-annapolis', 'Annapolis', 7),
    ('EAST', 'MD', 'Maryland', 'md-college-park', 'College Park', 8),
    ('EAST', 'MD', 'Maryland', 'md-salisbury', 'Salisbury', 9),
    ('EAST', 'MD', 'Maryland', 'md-laurel', 'Laurel', 10),
    # NJ - New Jersey (기존: bergen-hudson, middlesex-mercer + 0003)
    ('EAST', 'NJ', 'New Jersey', 'nj-woodbridge', 'Woodbridge', 6),
    ('EAST', 'NJ', 'New Jersey', 'nj-lakewood', 'Lakewood', 7),
    ('EAST', 'NJ', 'New Jersey', 'nj-toms-river', 'Toms River', 8),
    ('EAST', 'NJ', 'New Jersey', 'nj-hamilton', 'Hamilton', 9),
    ('EAST', 'NJ', 'New Jersey', 'nj-trenton', 'Trenton', 10),
    ('EAST', 'NJ', 'New Jersey', 'nj-clifton', 'Clifton', 11),
    ('EAST', 'NJ', 'New Jersey', 'nj-camden', 'Camden', 12),
    ('EAST', 'NJ', 'New Jersey', 'nj-brick', 'Brick', 13),
    ('EAST', 'NJ', 'New Jersey', 'nj-cherry-hill', 'Cherry Hill', 14),
    ('EAST', 'NJ', 'New Jersey', 'nj-passaic', 'Passaic', 15),
    # NY - New York (기존: manhattan-queens + 0003)
    ('EAST', 'NY', 'New York', 'ny-queens', 'Queens', 7),
    ('EAST', 'NY', 'New York', 'ny-bronx', 'Bronx', 8),
    ('EAST', 'NY', 'New York', 'ny-yonkers', 'Yonkers', 9),
    ('EAST', 'NY', 'New York', 'ny-utica', 'Utica', 10),
    ('EAST', 'NY', 'New York', 'ny-binghamton', 'Binghamton', 11),
    ('EAST', 'NY', 'New York', 'ny-newburgh', 'Newburgh', 12),
    ('EAST', 'NY', 'New York', 'ny-middletown', 'Middletown', 13),
    ('EAST', 'NY', 'New York', 'ny-kingston', 'Kingston', 14),
    ('EAST', 'NY', 'New York', 'ny-saratoga-springs', 'Saratoga Springs', 15),
    ('EAST', 'NY', 'New York', 'ny-poughkeepsie', 'Poughkeepsie', 16),
]


def add_cities(apps, schema_editor):
    Region = apps.get_model('community', 'Region')
    Area = apps.get_model('community', 'Area')
    region_map = {r.code: r for r in Region.objects.all()}
    for reg_code, state_code, state_name, slug, city_name, order in ALL_CITIES:
        region = region_map.get(reg_code)
        if not region:
            continue
        Area.objects.get_or_create(
            slug=slug,
            defaults={
                'region': region,
                'state_code': state_code,
                'state_name': state_name,
                'city_name': city_name,
                'order': order,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [('community', '0003_add_more_cities_by_state')]
    operations = [migrations.RunPython(add_cities, noop)]
